#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Load up virtualenvwrapper
virtualenvwrapper="$(which virtualenvwrapper.sh)"
if [[ ! -z "$virtualenvwrapper" ]]; then
	source "$virtualenvwrapper"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
